---
title: "Batman Timeline"
author: "Jared Braggins"
date: "11/09/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE)
```
```{r prep, message=FALSE, warning=FALSE, include=FALSE}
# Load libraries
library(tidyverse)
library(ggfittext)
library(knitr)
library(lubridate)
library(scales)
library(extrafont)
```
``` {r, message=FALSE, warning=FALSE, include=FALSE}
# Import data
b_data <- read.csv("https://query.data.world/s/ciop4tu2jbtu7k5ncjgor2hnrhzxhu", header=TRUE, stringsAsFactors=FALSE);
```
```{r, include=FALSE}
# Rename Year column, add column for live action or animated
b_data_format <- b_data %>% 
  rename(Year = ï..Year) %>% 
  mutate(Format = case_when(
    Title == "Batman" ~ "Live Action",
    Title == "Batman Returns" ~ "Live Action",
    Title == "Batman: Mask of the Phantasm" ~ "Animated",
    Title == "Batman Forever" ~ "Live Action",
    Title == "Batman & Robin" ~ "Live Action",
    Title == "Batman & Mr. Freeze: SubZero" ~ "Animated",
    Title == "Batman Beyond: Return of the Joker" ~ "Animated",
    Title == "Batman Begins" ~ "Live Action",
    Title == "The Dark Knight" ~ "Live Action",
    Title == "Batman: Under the Red Hood" ~ "Animated",
    Title == "Batman: Year One" ~ "Animated",
    Title == "Batman: The Dark Knight Returns, Part 1" ~ "Animated",
    Title == "The Dark Knight Rises" ~ "Live Action",
    Title == "Batman: The Dark Knight Returns, Part 2" ~ "Animated",
    Title == "Batman: Assault on Arkham" ~ "Animated",
    Title == "Batman v Superman" ~ "Live Action",
    Title == "Batman: The Killing Joke" ~ "Animated",
    Title == "Justice League" ~ "Live Action",
    Title == "Batman: Gotham by Gaslight" ~ "Animated"
  ), 
  Released = as.Date(Released, format = "%m/%d/%Y"),
  x_coord_1 = Released + 365,
  x_coord_2 = x_coord_1 + 365, 
  ID = c(1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1))

glimpse(b_data_format)
View(b_data_format)

#NOTE: I'm missing some movies, so will need data for those

#Create dataframe for legend
l_data <- b_data_format %>% 
  group_by(Format) %>%
  count(Format)
l_data$Format <- factor(l_data$Format) %>%
  fct_reorder(l_data$n)

t_data <- b_data_format %>%  
  select(ID, Title, Year, Released, x_coord_1, x_coord_2, Imdb.Rating, Format) 

# Separate directors
d_data <- b_data_format %>% 
  mutate(Director = ifelse(
    Director == "Eric Radomski, Bruce Timm, Kevin Altieri, Boyd Kirkland, Frank Paur, Dan Riba", "Various", 
    ifelse(Director == "Sam Liu, Lauren Montgomery", "Sam Liu,\nLauren Montgomery",
           ifelse(Director == "Jay Oliva, Ethan Spaulding", "Jay Oliva,\nEthan Spaulding", Director)))) %>% 
  group_by(Director,Format) %>%
  summarise(n = n()) %>% 
  mutate(Movie_Label = if_else(n == 1, glue::glue("{n} Film"), glue::glue("{n} Films"))) %>% 
  ungroup() 

d_data_top <- b_data_format %>% 
  select(Director, Released) %>% 
  mutate(Director = ifelse(
    Director == "Eric Radomski, Bruce Timm, Kevin Altieri, Boyd Kirkland, Frank Paur, Dan Riba", "Various", 
    ifelse(Director == "Sam Liu, Lauren Montgomery", "Sam Liu,\nLauren Montgomery",
           ifelse(Director == "Jay Oliva, Ethan Spaulding", "Jay Oliva,\nEthan Spaulding", Director)))) %>% 
  group_by(Director) %>% 
  filter(row_number()==1)

d_data <- left_join(d_data, d_data_top) %>% 
  arrange(Released) %>% 
  mutate(ID = c(1,0,1,0,1,0,1,0,1,0,1,0))

```
```{r, include=FALSE}
#Set theme
font_family <- 'Century Gothic'
background <- "#1D1D1D"
text_colour <- "white"
axis_colour <- "white"
plot_colour <- "black"
theme_style <- theme(text = element_text(family = font_family),
                     rect = element_rect(fill = background),
                     plot.background = element_rect(fill = background, color = NA),
                     plot.title = element_text(face = 'bold', size = 20, colour = text_colour),
                     plot.subtitle = element_text(size = 16, colour = text_colour),
                     plot.caption = element_text(size = 10, colour = text_colour),
                     plot.margin = unit(c(1, 1, 1, 1), "cm"),
                     panel.background = element_rect(fill = background, color = NA),
                     panel.border = element_blank(),
                     axis.title = element_blank(),
                     axis.ticks = element_blank(),
                     axis.line = element_blank(),
                     legend.position="none")

theme_set(theme_classic() + theme_style)

cols <- c("#ffff36", "#0fc3ff")
```


```{r, echo=FALSE, fig.width=12, fig.height = 5.3}
# Plot Timeline
ggplot(t_data, aes(Released, 0)) + 
  geom_hline(yintercept = 0, 
             color = axis_colour, 
             size = 0.3) +
  geom_hline(yintercept = -0.045,
             color = axis_colour, 
             size = 0.3, 
             linetype = "dashed") +
  #Film points
  geom_point(aes(y = 0, 
                 size = Imdb.Rating, 
                 colour = Format), 
             alpha = 0.5) +
  #Director points
  geom_point(data = d_data, 
             aes(y = -0.045, 
                 colour = Format), 
             shape = 5, 
             size = 6) +
  geom_segment(aes(x=Released, 
                   xend=x_coord_1, 
                   y=ifelse(ID == 1,.0015, -.0015), 
                   yend=ifelse(ID == 1,.02, -.02)), 
               size = .4, 
               color = axis_colour, 
               linetype = 1) +
  geom_segment(aes(x=x_coord_1,
                   xend=x_coord_2,
                   y=ifelse(ID == 1,.02, -.02), 
                   yend=ifelse(ID == 1,.02, -.02)), 
               size = .4, 
               color = axis_colour,
               linetype = 1) +
  #Title
  geom_text(aes(label = Title, 
                x = x_coord_1, 
                y = ifelse(ID == 1,.03, -.025)), 
            family = font_family, 
            fontface = "bold", 
            color = text_colour, 
            hjust = "left", 
            size = 4) +
  #Rating
  geom_text(aes(label = paste("Rating: ", Imdb.Rating), 
                x = x_coord_1, 
                y = ifelse(ID == 1,.027, -.028)), 
            family = font_family, 
            color = text_colour, 
            hjust = "left", 
            size = 4) +
  #Director
  geom_text(data = d_data, 
            aes(label = Director, 
                x = Released, 
                y = ifelse(ID == 1,-.040, -.048)), 
            fontface = "bold", 
            family = font_family, 
            color = text_colour, 
            hjust = "center", 
            size = 3) +
  #No. of Movies
  geom_text(data = d_data, 
            aes(x = Released,
                y = ifelse(ID == 1,-.042, -.051),
                label = Movie_Label),
            #nudge_y = -.002,
            family = font_family,
            color = text_colour,
            size = 3,
            hjust = "center") +
  scale_color_manual(values = cols) +
  theme(axis.text.x = element_text(size = 12, colour= text_colour),
        axis.text.y = element_text(size = 12, colour= text_colour)) +
  scale_y_continuous(limits = c(-0.052, 0.052)) +
  scale_x_date(limits = as.Date(c("1989-01-01","2021-01-01"))) +
  labs(title = "Batman Films",
       caption = "Visualisation: @JaredBraggins | Sources: IMDb & Kaggle")
  
```
```{r, echo=FALSE, fig.width=12, fig.height = 5.3}
#Export plot
ggsave("Batman Timeline.png", width = 420, height = 297, unit = "mm")
```
